name: 'Code Review using qwen2.5-coder'
description: 'Perform a code review on modified code using Ollama and Qwen LLM.'
author: 'Austin Songer'
branding:
  color: 'blue'
  icon: 'code'

inputs:
  llm-model:
    description: 'Name of the LLM model to use for code review.'
    required: true
    default: 'qwen2.5-coder:3b'
  github-token:
    description: 'GitHub token for accessing the repository and posting comments.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install and Start Ollama (CPU Mode)
      run: |
        # Install Ollama
        curl -fsSL https://ollama.com/install.sh | bash
        
        # Start Ollama in CPU-only mode
        nohup ollama serve --cpu > ollama.log 2>&1 &
        
        # Wait for Ollama to start
        for i in {1..10}; do
          if curl -s http://127.0.0.1:11434/health | grep "OK"; then
            echo "Ollama is running in CPU-only mode."
            exit 0
          fi
          echo "Waiting for Ollama to start..."
          sleep 5
        done
        echo "Ollama did not start in time."
        exit 1
      shell: bash

    - name: Get modified files
      id: get-modified-files
      uses: tj-actions/changed-files@v43

    - name: Review modified files
      run: |
        for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
          modified_file_review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "${{ inputs.llm-model }}", "prompt": "Review this code, provide suggestions for improvement, coding best practices, improve readability, and maintainability. Remove any code smells and anti-patterns. Provide code examples for your suggestion.:\n\n```\n$(cat $file)\n```", "stream": false}' | jq -r '.response')
          file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"
          echo "$file_comment" >> ollama_review.txt
        done

        # Post review comments to the pull request
        if [ -s ollama_review.txt ]; then
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
